package ir.sejadalmas.salesagent;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.text.InputType;import android.view.*;import android.widget.*;import org.json.*;
public class MainActivity extends Activity{
 final int NAVY=Color.rgb(23,39,54),GOLD=Color.rgb(218,139,0),BG=Color.rgb(249,249,250),MUTED=Color.rgb(118,124,132),LINE=Color.rgb(232,234,237); LinearLayout content; String base="https://sejadalmas.iq",token=""; Typeface regular,medium;
 public void onCreate(Bundle b){super.onCreate(b);regular=Typeface.create("sans-serif",Typeface.NORMAL);medium=Typeface.create("sans-serif-medium",Typeface.NORMAL);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);token=getPreferences(0).getString("token","");splash();}
 int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} GradientDrawable shape(int fill,int stroke,int r){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(r));if(stroke!=Color.TRANSPARENT)d.setStroke(dp(1),stroke);return d;}
 TextView tx(String s,int sp,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);v.setGravity(Gravity.RIGHT);v.setTypeface(b?medium:regular);v.setIncludeFontPadding(false);return v;}
 void splash(){FrameLayout f=new FrameLayout(this);f.setBackgroundColor(BG);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.almas_logo);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);box.addView(logo,new LinearLayout.LayoutParams(dp(210),dp(58)));TextView cap=tx("همراه فروش الماس",12,MUTED,false);cap.setGravity(Gravity.CENTER);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.topMargin=dp(14);box.addView(cap,cp);f.addView(box,new FrameLayout.LayoutParams(-1,-1));setContentView(f);new Handler(Looper.getMainLooper()).postDelayed(()->{if(token.isEmpty())login();else home();},650);}
 void frame(){FrameLayout page=new FrameLayout(this);page.setBackgroundColor(BG);View accent=new View(this);accent.setBackground(shape(Color.rgb(255,247,232),Color.TRANSPARENT,999));FrameLayout.LayoutParams ap=new FrameLayout.LayoutParams(dp(210),dp(210));ap.gravity=Gravity.TOP|Gravity.RIGHT;ap.topMargin=-dp(125);ap.rightMargin=-dp(95);page.addView(accent,ap);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);content.setPadding(dp(26),dp(14),dp(26),dp(24));sv.addView(content,new ScrollView.LayoutParams(-1,-1));page.addView(sv,new FrameLayout.LayoutParams(-1,-1));setContentView(page);}
 void gap(int h){content.addView(new Space(this),new LinearLayout.LayoutParams(1,dp(h)));}
 EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.rgb(172,176,181));e.setTextColor(NAVY);e.setTextSize(14);e.setTypeface(regular);e.setSingleLine();e.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);e.setPadding(dp(15),0,dp(15),0);e.setBackground(shape(Color.WHITE,LINE,13));return e;}
 Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setTypeface(medium);b.setBackground(shape(NAVY,NAVY,13));b.setElevation(0);b.setStateListAnimator(null);return b;}
 void login(){frame();gap(18);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.almas_logo);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(46));content.addView(logo,lp);gap(26);TextView title=tx("ورود",20,NAVY,true);content.addView(title);gap(5);content.addView(tx("با حساب کاربری فروش وارد شوید",12,MUTED,false));gap(22);content.addView(tx("ایمیل",12,NAVY,false));gap(7);EditText email=field("name@sejadalmas.iq");content.addView(email,new LinearLayout.LayoutParams(-1,dp(49)));gap(14);content.addView(tx("رمز عبور",12,NAVY,false));gap(7);EditText pass=field("رمز عبور");pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);content.addView(pass,new LinearLayout.LayoutParams(-1,dp(49)));gap(18);Button enter=primary("ورود");content.addView(enter,new LinearLayout.LayoutParams(-1,dp(48)));ProgressBar busy=new ProgressBar(this);busy.setVisibility(View.GONE);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(22),dp(22));bp.gravity=Gravity.CENTER;bp.topMargin=dp(12);content.addView(busy,bp);TextView msg=tx("",12,Color.rgb(176,63,63),false);msg.setGravity(Gravity.CENTER);LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(-1,-2);mp.topMargin=dp(10);content.addView(msg,mp);gap(22);TextView foot=tx("الماس کاشان  •  نسخه ۰.۱.۴",10,MUTED,false);foot.setGravity(Gravity.CENTER);content.addView(foot);
 enter.setOnClickListener(v->{String em=email.getText().toString().trim(),pw=pass.getText().toString();if(em.isEmpty()||pw.isEmpty()){msg.setText("ایمیل و رمز عبور را وارد کنید");return;}enter.setEnabled(false);enter.setText("در حال ورود…");busy.setVisibility(View.VISIBLE);msg.setText("");new Thread(()->{try{Api api=new Api(base,"");JSONObject h=api.health();if(!h.optBoolean("success"))throw new Exception("سرویس موبایل آماده نیست");JSONObject d=new JSONObject().put("email",em).put("password",pw).put("device","Android Sales Agent 0.1.4");JSONObject r=api.call("login","POST",d);runOnUiThread(()->{if(r.optBoolean("success")){token=r.optString("token");getPreferences(0).edit().putString("token",token).apply();home();}else reset(enter,busy,msg,r.optString("message","ورود انجام نشد"));});}catch(Exception e){runOnUiThread(()->reset(enter,busy,msg,e.getMessage()));}}).start();});}
 void reset(Button b,ProgressBar p,TextView m,String s){b.setEnabled(true);b.setText("ورود");p.setVisibility(View.GONE);m.setText(s);}
 void home(){frame();gap(22);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.almas_logo);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);content.addView(logo,new LinearLayout.LayoutParams(-1,dp(42)));gap(26);content.addView(tx("میز کار فروش",21,NAVY,true));gap(7);content.addView(tx("اتصال امن برقرار است",12,MUTED,false));gap(24);Button out=primary("خروج از حساب");content.addView(out,new LinearLayout.LayoutParams(-1,dp(46)));out.setOnClickListener(v->{getPreferences(0).edit().clear().apply();token="";login();});}
}
