package ir.sejadalmas.salesagent;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.Typeface;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import org.json.*;import java.text.DecimalFormat;
public class MainActivity extends Activity{
 final int NAVY=Color.rgb(25,39,55), GOLD=Color.rgb(199,154,66), BG=Color.rgb(247,248,250), MUTED=Color.rgb(105,116,128); LinearLayout root,content; String base,token; DecimalFormat nf=new DecimalFormat("#,###");
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);base=getPreferences(0).getString("base","");token=getPreferences(0).getString("token","");if(base.isEmpty()||token.isEmpty())login();else home();}
 TextView t(String s,int sp,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(color);v.setGravity(Gravity.RIGHT);v.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);v.setPadding(dp(4),dp(6),dp(4),dp(6));return v;}
 EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(15);e.setSingleLine(true);e.setGravity(Gravity.RIGHT);e.setPadding(dp(14),0,dp(14),0);e.setBackground(round(Color.WHITE,Color.rgb(225,229,234),14));e.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(52)));return e;}
 GradientDrawable round(int fill,int stroke,int r){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(r));d.setStroke(dp(1),stroke);return d;} int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(round(NAVY,NAVY,14));b.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(52)));return b;}
 void frame(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(14),dp(18),dp(14));root.setBackgroundColor(BG);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 void login(){frame();Space sp=new Space(this);content.addView(sp,new LinearLayout.LayoutParams(1,dp(70)));content.addView(t("الماس کاشان",26,NAVY,true));content.addView(t("اپ کارشناسان فروش",17,MUTED,false));gap(24);EditText server=input("آدرس سامانه، مثال: https://crm.example.com");server.setText(base);content.addView(server);gap(10);EditText email=input("ایمیل کارشناس");content.addView(email);gap(10);EditText pass=input("رمز عبور");pass.setInputType(0x81);content.addView(pass);gap(18);Button b=btn("ورود به حساب");content.addView(b);TextView msg=t("",13,Color.RED,false);content.addView(msg);b.setOnClickListener(v->{base=server.getText().toString().trim().replaceAll("/+$","");if(base.isEmpty()){msg.setText("آدرس سامانه را وارد کنید.");return;}b.setEnabled(false);new Thread(()->{try{JSONObject d=new JSONObject().put("email",email.getText()).put("password",pass.getText()).put("device","Android V1");JSONObject r=new Api(base,"").call("login","POST",d);runOnUiThread(()->{try{if(r.optBoolean("success")){token=r.getString("token");getPreferences(0).edit().putString("base",base).putString("token",token).apply();home();}else msg.setText(r.optString("message","ورود ناموفق"));}catch(Exception e){msg.setText(e.getMessage());}b.setEnabled(true);});}catch(Exception e){runOnUiThread(()->{msg.setText("ارتباط با سرور برقرار نشد: "+e.getMessage());b.setEnabled(true);});}}).start();});}
 void header(String title){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",30,NAVY,false);back.setOnClickListener(v->home());h.addView(back,new LinearLayout.LayoutParams(dp(45),dp(50)));TextView tt=t(title,20,NAVY,true);h.addView(tt,new LinearLayout.LayoutParams(0,dp(55),1));content.addView(h);gap(8);}
 void home(){frame();content.addView(t("سلام، روز خوبی داشته باشید",14,MUTED,false));content.addView(t("میز کار فروش",26,NAVY,true));gap(14);LinearLayout metrics=new LinearLayout(this);metrics.setOrientation(LinearLayout.HORIZONTAL);TextView a=metric("فروش ماه","…"),b=metric("وصول ماه","…");metrics.addView(a,new LinearLayout.LayoutParams(0,dp(105),1));space(metrics,8);metrics.addView(b,new LinearLayout.LayoutParams(0,dp(105),1));content.addView(metrics);gap(12);TextView goal=card("هدف من","در حال دریافت…");content.addView(goal);gap(12);TextView rank=card("رتبه و کمیسیون","در حال دریافت…");content.addView(rank);gap(18);content.addView(t("دسترسی سریع",16,NAVY,true));gap(8);navCard("ویترین و ثبت سفارش","مشاهده کالاها و ثبت درخواست فروش",()->catalog());navCard("عملکرد من","رتبه، فروش و کمیسیون",()->performance());navCard("واتساپ من","گفتگوهای تخصیص‌یافته",()->whatsapp());gap(16);TextView out=t("خروج از حساب",14,Color.rgb(180,55,55),false);out.setGravity(Gravity.CENTER);out.setOnClickListener(v->{getPreferences(0).edit().clear().apply();token="";login();});content.addView(out);new Thread(()->{try{JSONObject r=new Api(base,token).call("dashboard","GET",null);runOnUiThread(()->{JSONObject m=r.optJSONObject("month");if(m!=null){a.setText("فروش ماه\n"+money(m.optDouble("invoiced")));b.setText("وصول ماه\n"+money(m.optDouble("paid")));}JSONObject g=r.optJSONObject("goal");goal.setText(g==null?"هدف من\nهدف فعالی برای این دوره ثبت نشده است.":"هدف من\n"+g.optString("subject")+"\n"+money(g.optDouble("current"))+" از "+money(g.optDouble("target"))+"  •  "+g.optDouble("percent")+"٪");JSONObject k=r.optJSONObject("ranking");rank.setText(k==null?"رتبه و کمیسیون\nنتیجه رتبه‌بندی فعالی یافت نشد.":"رتبه و کمیسیون\n"+k.optString("rank")+"  •  فروش مبنا "+money(k.optDouble("sales"))+"\nکمیسیون نهایی "+money(k.optDouble("final_commission")));});}catch(Exception e){}}).start();}
 TextView metric(String l,String v){TextView x=t(l+"\n"+v,14,NAVY,true);x.setGravity(Gravity.CENTER);x.setBackground(round(Color.WHITE,Color.rgb(232,235,239),16));return x;} TextView card(String title,String body){TextView x=t(title+"\n"+body,15,NAVY,true);x.setMinHeight(dp(100));x.setPadding(dp(16),dp(14),dp(16),dp(14));x.setBackground(round(Color.WHITE,Color.rgb(232,235,239),16));return x;}
 void navCard(String title,String sub,Runnable r){TextView x=t(title+"\n"+sub,16,NAVY,true);x.setPadding(dp(16),dp(14),dp(16),dp(14));x.setBackground(round(Color.WHITE,Color.rgb(232,235,239),16));x.setOnClickListener(v->r.run());content.addView(x,new LinearLayout.LayoutParams(-1,dp(82)));gap(9);}
 void catalog(){frame();header("ویترین و فروش");EditText q=input("جستجو در نام یا کد کالا");content.addView(q);gap(10);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);Runnable load=()->new Thread(()->{try{String qs=URLEncoder.encode(q.getText().toString(),"UTF-8");JSONObject r=new Api(base,token).call("catalog?q="+qs,"GET",null);JSONArray ar=r.optJSONArray("items");runOnUiThread(()->{list.removeAllViews();for(int i=0;ar!=null&&i<ar.length();i++){JSONObject x=ar.optJSONObject(i);TextView v=card(x.optString("name"),x.optString("code")+"\n"+(x.optDouble("price")>0?money(x.optDouble("price")):"قیمت در مرحله سفارش کنترل می‌شود"));list.addView(v);gapIn(list,8);}});}catch(Exception e){}}).start();q.setOnEditorActionListener((v,a,e)->{load.run();return true;});load.run();}
 void performance(){frame();header("عملکرد من");LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);new Thread(()->{try{JSONArray a=new Api(base,token).call("performance","GET",null).optJSONArray("items");runOnUiThread(()->{if(a==null||a.length()==0){list.addView(card("هنوز نتیجه‌ای نیست","پس از محاسبه دوره رتبه‌بندی، نتیجه اینجا نمایش داده می‌شود."));return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);list.addView(card(x.optString("period"),"رتبه: "+x.optString("rank_name","—")+"\nفروش: "+money(x.optDouble("sales_amount"))+"\nکمیسیون نهایی: "+money(x.optDouble("final_commission"))));gapIn(list,8);}});}catch(Exception e){}}).start();}
 void whatsapp(){frame();header("واتساپ من");LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);new Thread(()->{try{JSONArray a=new Api(base,token).call("whatsapp","GET",null).optJSONArray("items");runOnUiThread(()->{if(a==null||a.length()==0){list.addView(card("پیامی ندارید","در حال حاضر گفتگویی به شما تخصیص داده نشده است."));return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);String name=x.optString("contact_name",x.optString("wa_id","مشتری"));TextView v=card(name,x.optString("last_message_body","گفتگوی تخصیص‌یافته")+"\n"+x.optString("last_message_at",""));list.addView(v);gapIn(list,8);}});}catch(Exception e){}}).start();}
 String money(double d){return nf.format(d)+" د.ع";} void gap(int h){content.addView(new Space(this),new LinearLayout.LayoutParams(1,dp(h)));} void gapIn(LinearLayout l,int h){l.addView(new Space(this),new LinearLayout.LayoutParams(1,dp(h)));} void space(LinearLayout l,int w){l.addView(new Space(this),new LinearLayout.LayoutParams(dp(w),1));}
}
