package ir.sejadalmas.salesagent;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.text.InputType;import android.view.*;import android.widget.*;import org.json.*;
public class MainActivity extends Activity{
 final int NAVY=Color.rgb(24,39,56),GOLD=Color.rgb(218,139,0),BG=Color.rgb(247,248,250),MUTED=Color.rgb(105,116,128),LINE=Color.rgb(226,230,235);LinearLayout root,content;String base,token;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);base=getPreferences(0).getString("base","https://sejadalmas.iq");token=getPreferences(0).getString("token","");splash();}
 int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int fill,int stroke,int r){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(r));d.setStroke(dp(1),stroke);return d;}
 TextView text(String s,int sp,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);v.setGravity(Gravity.RIGHT);v.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);return v;}
 void baseFrame(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(24),dp(18),dp(24),dp(24));content.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);sv.addView(content,new ScrollView.LayoutParams(-1,-1));root.addView(sv,new LinearLayout.LayoutParams(-1,-1));setContentView(root);}
 void splash(){LinearLayout s=new LinearLayout(this);s.setOrientation(LinearLayout.VERTICAL);s.setGravity(Gravity.CENTER);s.setPadding(dp(30),0,dp(30),0);s.setBackgroundColor(Color.WHITE);ImageView logo=new ImageView(this);logo.setImageResource(ir.sejadalmas.salesagent.R.drawable.almas_logo);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);s.addView(logo,new LinearLayout.LayoutParams(-1,dp(105)));Space gap=new Space(this);s.addView(gap,new LinearLayout.LayoutParams(1,dp(28)));ProgressBar p=new ProgressBar(this);s.addView(p,new LinearLayout.LayoutParams(dp(30),dp(30)));TextView cap=text("سامانه همراه کارشناسان فروش",14,MUTED,false);cap.setGravity(Gravity.CENTER);cap.setPadding(0,dp(18),0,0);s.addView(cap);setContentView(s);new Handler(Looper.getMainLooper()).postDelayed(()->{if(token.isEmpty())login();else home();},1100);}
 EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(15);e.setSingleLine(true);e.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);e.setPadding(dp(16),0,dp(16),0);e.setBackground(bg(Color.WHITE,LINE,16));e.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(58)));return e;}
 Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(15);b.setTextColor(Color.WHITE);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(bg(NAVY,NAVY,16));b.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(58)));return b;}
 void gap(int h){content.addView(new Space(this),new LinearLayout.LayoutParams(1,dp(h)));}
 void login(){baseFrame();gap(36);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.almas_logo);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);content.addView(logo,new LinearLayout.LayoutParams(-1,dp(92)));gap(22);TextView title=text("ورود به حساب کاربری",24,NAVY,true);title.setGravity(Gravity.CENTER);content.addView(title);gap(7);TextView sub=text("برای ورود، اطلاعات حساب کارشناس فروش را وارد کنید",14,MUTED,false);sub.setGravity(Gravity.CENTER);content.addView(sub);gap(30);TextView sl=text("آدرس سامانه",13,NAVY,true);content.addView(sl);gap(7);EditText server=field("sejadalmas.iq");server.setText(base);content.addView(server);gap(15);content.addView(text("ایمیل کارشناس",13,NAVY,true));gap(7);EditText email=field("name@sejadalmas.iq");content.addView(email);gap(15);content.addView(text("رمز عبور",13,NAVY,true));gap(7);EditText pass=field("رمز عبور");pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);content.addView(pass);gap(22);Button enter=button("ورود به سامانه");content.addView(enter);gap(12);ProgressBar busy=new ProgressBar(this);busy.setVisibility(View.GONE);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(28),dp(28));bp.gravity=Gravity.CENTER;content.addView(busy,bp);gap(8);TextView msg=text("",13,Color.rgb(185,48,48),false);msg.setGravity(Gravity.CENTER);content.addView(msg);gap(24);TextView foot=text("الماس کاشان • اپلیکیشن کارشناسان فروش",12,MUTED,false);foot.setGravity(Gravity.CENTER);content.addView(foot);
  enter.setOnClickListener(v->{String em=email.getText().toString().trim(),pw=pass.getText().toString();base=Api.normalize(server.getText().toString());server.setText(base);if(em.isEmpty()||pw.isEmpty()){msg.setText("ایمیل و رمز عبور را وارد کنید.");return;}msg.setText("");enter.setEnabled(false);enter.setText("در حال ورود…");busy.setVisibility(View.VISIBLE);new Thread(()->{try{JSONObject d=new JSONObject().put("email",em).put("password",pw).put("device","Android Sales Agent");JSONObject r=new Api(base,"").call("login","POST",d);runOnUiThread(()->{if(r.optBoolean("success")){token=r.optString("token");getPreferences(0).edit().putString("base",base).putString("token",token).apply();home();}else{msg.setText(r.optString("message","ورود انجام نشد."));enter.setEnabled(true);enter.setText("ورود به سامانه");busy.setVisibility(View.GONE);}});}catch(Exception e){runOnUiThread(()->{msg.setText(e.getMessage());enter.setEnabled(true);enter.setText("ورود به سامانه");busy.setVisibility(View.GONE);});}}).start();});}
 void home(){baseFrame();gap(28);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.almas_logo);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);content.addView(logo,new LinearLayout.LayoutParams(-1,dp(68)));gap(22);content.addView(text("میز کار فروش",26,NAVY,true));gap(8);content.addView(text("اتصال به سامانه برقرار است. توسعه داشبورد، ویترین، عملکرد و واتساپ روی همین نسخه ادامه می‌یابد.",15,MUTED,false));gap(24);Button out=button("خروج از حساب");content.addView(out);out.setOnClickListener(v->{getPreferences(0).edit().clear().apply();token="";login();});}
}
